jobDefs:
  - repo: players
    image: wrgl/wrgl-examples-fifa-20:0.1.0
    command:
      - python
      - players.py
    sourceRepos:
      - players_15
      - players_16
      - players_17
      - players_18
      - players_19
      - players_20
  - repo: player_attrs
    image: wrgl/wrgl-examples-fifa-20:0.1.0
    command:
      - python
      - player_attrs.py
    sourceRepos:
      - players_15
      - players_16
      - players_17
      - players_18
      - players_19
      - players_20
